# Generated by Django 4.2.3 on 2023-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='car_image'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='car_image'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='car_image'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='car_image'),
        ),
        migrations.AlterField(
            model_name='car',
            name='generation',
            field=models.CharField(max_length=50),
        ),
    ]
