# Generated by Django 4.2.3 on 2023-08-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_car', '0003_manufacture_car_manufacture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainpage_car.body'),
        ),
    ]
