# Generated by Django 4.2.3 on 2023-09-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('mainpage_car', '0007_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.manager'),
        ),
    ]
