# Generated by Django 4.2.3 on 2023-10-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_car', '0009_alter_car_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
            ],
        ),
    ]
