# Generated by Django 4.2.3 on 2023-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_bill_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
